const TOGGLE_APPLET = 'TOGGLE_APPLET';
const TOGGLE_SERVICE = 'TOGGLE_SERVICE';
const UPDATE_SERVICES = 'UPDATE_SERVICES';
const UPDATE_APPLETS = 'UPDATE_APPLETS';

export {
    TOGGLE_APPLET,
    TOGGLE_SERVICE,
    UPDATE_SERVICES,
    UPDATE_APPLETS
}