const LOG_IN = 'LOG_IN';
const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
const LOG_OUT = 'LOG_OUT';

const LOG_IN_GOOGLE_SUCCESS = 'LOG_IN_GOOGLE_SUCCESS';
const LOG_IN_GOOGLE_FAILURE = 'LOG_IN_GOOGLE_FAILURE';
const LOG_OUT_GOOGLE = 'LOG_OUT_GOOGLE';

const LOG_IN_FACEBOOK_SUCCESS = 'LOG_IN_FACEBOOK_SUCCESS';
const LOG_IN_FACEBOOK_FAILURE = 'LOG_IN_FACEBOOK_FAILURE';
const LOG_OUT_FACEBOOK = 'LOG_OUT_FACEBOOK';

const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

const TOKEN = 'TOKEN';

export {
    LOG_IN,
    LOG_IN_SUCCESS,
    LOG_IN_FAILURE,
    LOG_OUT,
    LOG_IN_GOOGLE_SUCCESS,
    LOG_IN_GOOGLE_FAILURE,
    LOG_OUT_GOOGLE,
    LOG_IN_FACEBOOK_SUCCESS,
    LOG_IN_FACEBOOK_FAILURE,
    LOG_OUT_FACEBOOK,
    SIGN_UP,
    SIGN_UP_SUCCESS,
    SIGN_UP_FAILURE,
    TOKEN,
};
